services:
  - type: web
    name: fuel-stations-backend
    env: node
    buildCommand: npm install; npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
    disk:
      name: node_modules
      mountPath: /opt/render/project/src/node_modules